#!/bin/bash

# Get the current directory
CWD=`pwd`
DATE=`date`
TPL_SHA=""

# Build all content available.
hugo --theme=dav3.co

# Enter the 'public' submodule.
echo -e "\033[0;33m Pushing changes generated by Hugo.\033[0m\n\n"
pushd "$CWD/public"

  # Do the work.
  git add . &&
  git commit -s -m "Auto deployment of updated assets @ $DATE" &&
  git push --set-upstream origin master &&

  TPL_SHA="- $(git rev-parse HEAD)"

# Exit the directory back to the site-source repo.
popd

# Update the public SHA-ref.
echo -e "\033[0;33m Updating 'public' SHA.\033[0m\n\n"

# Update the SHA and push.
git add public/ &&
git commit -s -m "Updating public SHA $TPL_SHA @ $DATE" &&
git push &&

echo -e "\033[0;33m Done, go check out the updates.\033[0m\n\n"
